"""empty message

Revision ID: 6b24fd3a5ae0
Revises: 
Create Date: 2021-03-31 20:17:41.414417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b24fd3a5ae0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fizz_count', sa.Integer(), nullable=True),
    sa.Column('buzz_count', sa.Integer(), nullable=True),
    sa.Column('fizz_name', sa.String(), nullable=True),
    sa.Column('buzz_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variables')
    # ### end Alembic commands ###
